[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$PackagePath,
    [string]$ReportPath = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$packageName = "FormatFoundry.Development"
$packagePathResolved = (Resolve-Path -LiteralPath $PackagePath).Path
if (-not $ReportPath) { $ReportPath = Join-Path $PSScriptRoot "..\build\msix\installed-validation.json" }
$ReportPath = [IO.Path]::GetFullPath($ReportPath)
$report = [ordered]@{ ok = $false; package_path = $packagePathResolved; package_sha256 = (Get-FileHash -LiteralPath $packagePathResolved -Algorithm SHA256).Hash.ToLowerInvariant(); cleanup_passed = $false; probes = @{} }
$installedPackage = $null
$probeDirectory = $null

try {
    $principal = [Security.Principal.WindowsPrincipal]::new([Security.Principal.WindowsIdentity]::GetCurrent())
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "Run this isolated development-package test in an administrator PowerShell on Windows 11."
    }
    if ([Environment]::OSVersion.Version.Build -lt 22000) { throw "Unsigned development MSIX testing requires Windows 11." }
    if (Get-AppxPackage -AllUsers -Name $packageName) {
        throw "An existing development package was found. This test will not replace it or erase its settings."
    }
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $archive = [IO.Compression.ZipFile]::OpenRead($packagePathResolved)
    try {
        $reader = [IO.StreamReader]::new($archive.GetEntry("AppxManifest.xml").Open())
        try { [xml]$manifest = $reader.ReadToEnd() } finally { $reader.Dispose() }
        if ($manifest.Package.Identity.Name -ne $packageName -or $manifest.Package.Identity.Publisher -notlike '*OID.2.25.311729368913984317654407730594956997722=1*') {
            throw "Only the isolated FormatFoundry.Development unsigned candidate can be tested by this script."
        }
    } finally { $archive.Dispose() }
    Add-AppxPackage -Path $packagePathResolved -AllowUnsigned
    $installedPackage = Get-AppxPackage -Name $packageName
    if (-not $installedPackage) { throw "The development package did not register for this user." }
    $report.package_full_name = $installedPackage.PackageFullName
    $report.package_family_name = $installedPackage.PackageFamilyName
    $probeDirectory = Join-Path ([IO.Path]::GetTempPath()) ("format-foundry-msix-probe-" + [guid]::NewGuid().ToString("N"))
    New-Item -ItemType Directory -Path $probeDirectory | Out-Null
    foreach ($name in @("FormatFoundry.exe", "FormatFoundry_Updater.exe")) {
        $executable = Join-Path $installedPackage.InstallLocation "App\$name"
        $stdout = Join-Path $probeDirectory "$name.json"
        $stderr = Join-Path $probeDirectory "$name.stderr.txt"
        $process = Start-Process -FilePath $executable -ArgumentList "--smoke-test" -WorkingDirectory $probeDirectory -WindowStyle Hidden -RedirectStandardOutput $stdout -RedirectStandardError $stderr -PassThru
        $null = $process.Handle
        if (-not $process.WaitForExit(60000)) { $process.Kill(); throw "$name installed probe timed out." }
        $process.Refresh()
        $rawOutput = [IO.File]::ReadAllText($stdout)
        $rawError = [IO.File]::ReadAllText($stderr)
        $report.probes[$name] = @{ exit_code = $process.ExitCode; stdout = $rawOutput; stderr = $rawError }
        if ($process.ExitCode -ne 0) { throw "$name installed probe failed (exit $($process.ExitCode)): $rawError" }
        $payload = $rawOutput | ConvertFrom-Json
        if ($payload.extra.windows_package.package_family -ne $installedPackage.PackageFamilyName) {
            throw "$name did not receive its installed package identity."
        }
        $expectedSettings = Join-Path $env:LOCALAPPDATA "Packages\$($installedPackage.PackageFamilyName)\LocalState\FormatFoundry"
        if ($payload.paths.settings_dir -ne $expectedSettings) { throw "$name selected an incorrect settings directory." }
        $report.probes[$name] = @{ exit_code = $process.ExitCode; environment = $payload }
    }
    $report.ok = $true
} catch {
    $report.error = $_.Exception.Message
    $report.failure_location = $_.InvocationInfo.PositionMessage
} finally {
    if ($installedPackage) {
        try {
            Remove-AppxPackage -Package $installedPackage.PackageFullName
            $report.cleanup_passed = -not [bool](Get-AppxPackage -Name $packageName)
        } catch { $report.cleanup_error = $_.Exception.Message; $report.ok = $false }
    }
    if ($probeDirectory -and (Test-Path -LiteralPath $probeDirectory)) {
        # This path is newly generated by this script, never supplied by the caller.
        $resolvedProbe = [IO.Path]::GetFullPath($probeDirectory)
        $tempRoot = [IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\') + '\'
        if ($resolvedProbe.StartsWith($tempRoot, [StringComparison]::OrdinalIgnoreCase) -and (Split-Path $resolvedProbe -Leaf) -like 'format-foundry-msix-probe-*') {
            Remove-Item -LiteralPath $resolvedProbe -Recurse -Force
        }
    }
    New-Item -ItemType Directory -Path (Split-Path $ReportPath) -Force | Out-Null
    [IO.File]::WriteAllText($ReportPath, ($report | ConvertTo-Json -Depth 30), [Text.UTF8Encoding]::new($false))
}
if (-not $report.ok) { throw "Installed MSIX validation failed. See $ReportPath" }
Write-Host "Installed app/updater probes and uninstall passed: $ReportPath"
